apiVersion: v1
kind: Secret
metadata:
  name: {{ include "store-woocommerce.mariadbSecretName" . }}
  labels:
    {{- include "store-woocommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.mariadb.auth.password | quote }}
  root-password: {{ .Values.mariadb.auth.rootPassword | quote }}
