apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "store-woocommerce.fullname" . }}-mariadb
  labels:
    {{- include "store-woocommerce.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "store-woocommerce.fullname" . }}-mariadb
  replicas: 1
  selector:
    matchLabels:
      {{- include "store-woocommerce.selectorLabelsMariadb" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "store-woocommerce.selectorLabelsMariadb" . | nindent 8 }}
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          args:
            - "--skip-ssl"
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "store-woocommerce.mariadbSecretName" . }}
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "store-woocommerce.mariadbSecretName" . }}
                  key: root-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.mariadb.storageClass }}
        storageClassName: {{ .Values.mariadb.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mariadb.storage }}
