apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-woocommerce.fullname" . }}-mariadb
  labels:
    {{- include "store-woocommerce.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  selector:
    {{- include "store-woocommerce.selectorLabelsMariadb" . | nindent 4 }}
