apiVersion: v1
kind: ResourceQuota
metadata:
  name: store-quota
spec:
  hard:
    requests.cpu: "700m"
    requests.memory: "1.5Gi"
    limits.cpu: "1500m"
    limits.memory: "3Gi"
    pods: "6"
    services: "6"
    persistentvolumeclaims: "5"
    requests.storage: "5Gi"
