apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-woocommerce.fullname" . }}-wordpress
  labels:
    {{- include "store-woocommerce.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "store-woocommerce.selectorLabelsWordpress" . | nindent 4 }}
