apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa-backend
  template:
    metadata:
      labels:
        app: medusa-backend
    spec:
      containers:
        - name: medusa
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "start"]
          env:
            - name: DATABASE_URL
              value: postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?sslmode=disable

            - name: JWT_SECRET
              value: supersecret
            - name: COOKIE_SECRET
              value: supersecret
            - name: NODE_ENV
              value: production
            - name: STORE_CORS
              value: "*"
            - name: ADMIN_CORS
              value: "*"
            - name: AUTH_CORS
              value: "*"

          ports:
            - containerPort: {{ .Values.backend.port }}

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
