apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "store-medusa.fullname" . }}-postgres
spec:
  serviceName: {{ include "store-medusa.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "store-medusa.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "store-medusa.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "store-medusa.fullname" . }}-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "store-medusa.fullname" . }}-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "store-medusa.fullname" . }}-secrets
                  key: postgres-password
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-medusa.fullname" . }}-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: {{ include "store-medusa.fullname" . }}-postgres
