{{- if and .Values.resourceQuota .Values.resourceQuota.enabled -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "store-medusa.fullname" . }}-quota
  labels:
    {{- include "store-medusa.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}

