apiVersion: v1
kind: ResourceQuota
metadata:
  name: store-quota
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: "3Gi"
    limits.cpu: "3"
    limits.memory: "6Gi"
    pods: "5"
    services: "3"
