apiVersion: v1
kind: Secret
metadata:
  name: {{ include "store-medusa.fullname" . }}-secrets
type: Opaque
stringData:
  postgres-password: "medusa_password"
  postgres-db: "medusa_db"
  postgres-user: "medusa_user"
  jwt-secret: "super-secret-jwt"
  cookie-secret: "super-secret-cookie"
