store:
  name: medusa-test
  domain: medusa-test.127.0.0.1.nip.io

postgres:
  user: medusa
  password: medusa123
  database: medusa
  storage: 1Gi

backend:
  image: adc47/medusa-backend:local
  port: 9000

storefront:
  image: adc47/medusa-storefront:local
  port: 8000



admin:
  email: admin@example.com
  password: supersecret
  firstName: Admin
  lastName: User

bootstrap:
  region:
    name: US
    currency: usd
    country: US

resourceQuota:
  enabled: false

limitRange:
  enabled: false

networkPolicy:
  enabled: false
